//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenDaysToDieModCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ThisNeedsToBeSet")]
        public string ModTagSetting {
            get {
                return ((string)(this["ModTagSetting"]));
            }
            set {
                this["ModTagSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModInfoName {
            get {
                return ((string)(this["ModInfoName"]));
            }
            set {
                this["ModInfoName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModInfoDescription {
            get {
                return ((string)(this["ModInfoDescription"]));
            }
            set {
                this["ModInfoDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModInfoAuthor {
            get {
                return ((string)(this["ModInfoAuthor"]));
            }
            set {
                this["ModInfoAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModInfoVersion {
            get {
                return ((string)(this["ModInfoVersion"]));
            }
            set {
                this["ModInfoVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameFolderModDirectory {
            get {
                return ((string)(this["GameFolderModDirectory"]));
            }
            set {
                this["GameFolderModDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoLogTimestampOnSave {
            get {
                return ((bool)(this["DoLogTimestampOnSave"]));
            }
            set {
                this["DoLogTimestampOnSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoMoveMod {
            get {
                return ((bool)(this["AutoMoveMod"]));
            }
            set {
                this["AutoMoveMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoMoveDecisionMade {
            get {
                return ((bool)(this["AutoMoveDecisionMade"]));
            }
            set {
                this["AutoMoveDecisionMade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeChildrenSearchTreeTooltip {
            get {
                return ((bool)(this["IncludeChildrenSearchTreeTooltip"]));
            }
            set {
                this["IncludeChildrenSearchTreeTooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeCommentsSearchTreeTooltip {
            get {
                return ((bool)(this["IncludeCommentsSearchTreeTooltip"]));
            }
            set {
                this["IncludeCommentsSearchTreeTooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeAllModsObjectTreeAttributes {
            get {
                return ((bool)(this["IncludeAllModsObjectTreeAttributes"]));
            }
            set {
                this["IncludeAllModsObjectTreeAttributes"] = value;
            }
        }
    }
}
